### PR TITLE
Add STANDARD_NO_PAD configuration.

### PR DESCRIPTION
**Pull request by mrijkeboer**
This adds a STANDARD_NO_PAD configuration option.

### CODE REVIEW

**Comment by marshallpierce** [comment]
LGTM. @alicemaz WDYT?

**Comment by mrijkeboer** [comment]
Any update on this? If this is not wanted, would it be an option to make the fields of the `struct Config` public so I can make a static Config myself?

**Comment by marshallpierce** [comment]
I could merge it, but I can't publish to crates.io, so it wouldn't do you much good, unfortunately.

**Comment by mrijkeboer** [comment]
@marshallpierce: I would still appreciate you merging it. That way, it will be available in the next release on crates.io.

**Comment by mrijkeboer** [comment]
Thanks.

**Pull request merged**
