### PR TITLE
Make Config somewhat follow the Builder pattern

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
Cc @marshallpierce 

Note that this is not a breaking change, which is nice.

**Comment by nox** [comment]
I completely forgot to actually finish patching the tests ah ah. I'll fix that tomorrow.

**Comment by nox** [comment]
I fixed the tests.

**Comment by marshallpierce** [comment]
Released, plus some small renaming for clarity.

**Pull request merged**
