### PR TITLE
Add the `crypt(3)` character set

### PR DESCRIPTION
**Pull request by tjamaan**
Add the `crypt(3)` character set. This character set is used by the `crypt(3)` C function commonly used in password hashing (e.g. `/etc/passwd` in Linux, hashed passwords stored in databases, etc...).

### CODE REVIEW

**Comment by marshallpierce** [comment]
Thanks for the contribution. It looks like you left out the change to `make_tables.rs`, though.

**Comment by tjamaan** [comment]
Please let me know if I missed anything else 🙂

**Comment by tjamaan** [comment]
PS: I wanted to use inclusive ranges but they are not yet stable.

**Comment by marshallpierce** [comment]
Thanks. I'll take a detailed look as soon as I can, but it might be a week or so.

**Comment by marshallpierce** [comment]
Looks good, thanks. I'll release this as 0.9.1.

**Pull request merged**
